name: ff_annotation_route_library
description: The library for ff_annotation_route.
version: 1.2.3-nullsafety
homepage: https://github.com/fluttercandies/ff_annotation_route_library

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  ff_annotation_route_core: ^1.1.1-nullsafety
  flutter:
    sdk: flutter

